language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

branches:
  only:
    - master

install:
  - composer install
  - composer update phpunit/phpunit --with-dependencies

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
